var CARRIERS = {
    "GAL": "Galena Air Service",
    "HAR": "Friendship Air Alaska",
    "AAR": "Altair Airlines Inc.",
    "TN": "Air Tahiti Nui",
    "LOQ": "Lorair Ltd.",
    "MAE": "Mid-Atlantic Exp. Airlines",
    "TGQ": "Tranps Aereos Guatemaltecos",
    "UA": "United Air Lines Inc.",
    "RED": "Aerosun International Airlines Inc.",
    "ACP": "Air Chaparral Inc.",
    "GSA": "Golden Gate Airlines Inc.",
    "OPQ": "Orion Air",
    "PCQ": "Pace Airlines",
    "SH": "Servicio Aereo De Honduras",
    "ATN": "Air Atlantic Airlines Inc.",
    "KTQ": "Turks Air Ltd.",
    "TCE": "Oceanair Line",
    "QO": "Aeromexpress",
    "MIS": "Midstate Airlines Inc.",
    "XK": "Aerotal",
    "EPA": "Empire Airlines Inc.",
    "CTL": "Coastal Air Transport",
    "HUB": "Skystream Airlines",
    "IN": "Aerlinte Eireann Teoranta",
    "SPH": "Spirit Helicopter",
    "HIQ": "Business Flights Ltd.",
    "SAI": "Seair Alaska Airlines Inc.",
    "WAI": "Wise Airlines Inc.",
    "TAN": "Tanana Air Service",
    "FE": "Primaris Airlines Inc.",
    "OR": "TUI Airlines Nederland B.V.",
    "SE": "Das Air Cargo",
    "UNQ": "Overseas National Airways",
    "NXQ": "North Vancouver Air",
    "PHL": "Phillips Airlines",
    "RIQ": "Rich International Airways",
    "EUQ": "Air Atlanta Europe",
    "CMR": "Commuter Airlines",
    "02Q": "Titan Airways",
    "TYE": "Temsco Airlines",
    "XL": "Lan Ecuador",
    "X4": "Air Excursions LLC",
    "TG": "Thai Airways International Ltd.",
    "AAT": "Air Sunshine Inc.",
    "0IQ": "Lynx Aviation d/b/a Frontier Airlines",
    "SSA": "S. S. Airways Inc.",
    "AED": "Air East Of Delaware Inc.",
    "XC": "Air Caribbean",
    "XAC": "Air Express International Airlines",
    "ESQ": "Seagreen Air Transport",
    "BG": "Biman Bangladesh Airlines",
    "GSL": "Golden South Airlines Inc.",
    "VR": "Transportes Aereos De Cabo",
    "TRA": "Aeromexico Travel",
    "NN": "Northward Airlines Ltd.",
    "2GQ": "Cavok Air LLC",
    "K3": "Venture Travel LLC d/b/a Taquan Air Service",
    "RO": "Tarom Romanian Air Transpor",
    "JQ": "Jetstar Airways Pty Limited",
    "SKJ": "Sky-Jet",
    "RAQ": "Arista International Airlines Inc.",
    "VA": "Venezuelan International Airways",
    "AT": "Royal Air Maroc",
    "SSP": "Southern Seaplane",
    "IDQ": "Intl Air Service Co. Ltd.",
    "XAA": "Aero Union Corp",
    "MGQ": "Montana Austria Flugetrieb",
    "WET": "Western Charter Inc.",
    "ZIA": "Air New Mexico",
    "37": "Zeal 320",
    "BOI": "Bo-S-Aire Airlines Inc.",
    "7Z": "Lb Limited",
    "HSV": "Harbor Air Service",
    "BW": "Caribbean Airlines Limited",
    "WAW": "Westward Airways Inc.",
    "MQ": "American Eagle Airlines Inc.",
    "ER": "DHL Airways",
    "JTA": "Jetaire Airlines Inc.",
    "TLQ": "Trans-Mediterranean Airways",
    "ANB": "Air Nebraska Inc.",
    "2NQ": "LIMA NY Corp d/b/a Fly The Whale d/b/a Tailwind",
    "TH": "Transmile Air Service",
    "SG": "Jetsgo",
    "CAZ": "CAT Aviation",
    "MKQ": "Airmark Corporation",
    "F2": "Omega Air Holdings d/b/a Focus Air",
    "AMR": "AvAir",
    "GJ": "Mexicargo",
    "O6": "Oceanair Linhas Aereas S A",
    "P9": "Pro Air Inc.",
    "ALU": "Aleutian Air",
    "HAG": "Hageland Aviation Service",
    "YX": "Republic Airlines",
    "ANC": "Atlantic Air",
    "EY": "Etihad Airways",
    "4W": "Warbelow",
    "VS": "Virgin Atlantic Airways",
    "QH": "Air Florida Inc.",
    "CI": "China Airlines Ltd.",
    "2U": "Valley Air Express Inc.",
    "MLL": "Miller Air Transportersinc",
    "EK": "Emirates",
    "AUX": "Austin Express Inc.",
    "SS": "Corsair",
    "2PQ": "21 Air LLC",
    "COU": "Courtesy Air Service Inc.",
    "0Z": "Island Air Service",
    "CM": "Compania Panamena",
    "LZ": "Balkan Bulgarian Airlines",
    "KS": "Peninsula Airways Inc.",
    "APS": "Air Spirit Inc.",
    "SX": "Skybus Airlines Inc.",
    "VK": "Air Tungaru Corporation",
    "ZW": "Air Wisconsin Airlines Corp",
    "NJE": "NetJets Transportes Aereos S.A.",
    "HPZ": "Pacific Coast Airlines",
    "CRE": "Caribbean Express Inc.",
    "EQ": "Tame Linea Aerea del Ecuador Tme EP",
    "ASW": "Sunrise Airlines Inc.",
    "JH": "Amerijet International",
    "MYQ": "Lineas Aereas Mayas",
    "BAR": "Bard-Air Corp.",
    "CHE": "Charter Airlines",
    "SUI": "Sun International Airways",
    "AMA": "North American Airlines Inc.",
    "NRN": "Northern Airlines Inc.",
    "UX": "Air Europa",
    "JL": "Japan Air Lines Co. Ltd.",
    "WAQ": "Air Charter Systems",
    "N8": "National Air Cargo Group Inc d/ba National Airlines",
    "6H": "Israir Airlines",
    "JMA": "Jim Air Inc.",
    "RL": "Airline Of The Americas",
    "NK": "Spirit Air Lines",
    "1MQ": "Twin Cities Air Service LLC",
    "KI": "Time Air Ltd.",
    "MU": "China Eastern Airlines",
    "LB": "Lloyd Aereo Boliviano S. A.",
    "SKM": "Scheduled Skyways",
    "XBZ": "Air Natl Aircraft Sal & Ser",
    "LKN": "Loken Aviation",
    "SYB": "Skybus Express Airlines",
    "MET": "Metroplex Airlines",
    "BIA": "Big Island Air",
    "EET": "Exec Express II",
    "1UQ": "Gainjet Aviation SA",
    "Q2": "Zambia Airways Corp.",
    "BOA": "Boise Air Service",
    "HRA": "Trans-National Airlines Haw",
    "PCL": "Pacific Cal Air",
    "ZK": "Great Lakes Aviation Ltd.",
    "PRV": "Aloha Island Air",
    "0KQ": "Mokulele Flight Services Inc.",
    "VC": "Servicios Avensa",
    "TKQ": "Trans-Air-Link Corporation",
    "SVW": "Global Jet Luxembourg Sa",
    "WRT": "Wright Airlines Inc.",
    "04Q": "Tradewind Aviation",
    "XBT": "Pacific Alaska Airlines Inc.",
    "GM": "Air America",
    "9K": "Cape Air",
    "NLQ": "Nolinor Aviation",
    "BUQ": "Blue Bell Inc.",
    "SHS": "Shasta Air Inc.",
    "BZQ": "Abaco Air Ltd.",
    "ROY": "Royal American Airways Inc.",
    "ILL": "Air Illinois Inc.",
    "8J": "Jetall Airways",
    "CJQ": "Air Caribbean",
    "KET": "Ketchikan Air Service",
    "BGQ": "Airbus Transport Internat'l",
    "MRC": "Marco Island Airways Inc.",
    "DL": "Delta Air Lines Inc.",
    "MLX": "Merlin Express",
    "WFT": "Westflight Aviation",
    "ACS": "Alamo Commuter Airlines",
    "17Q": "Albinati Aeronautics SA",
    "WRA": "Wra Inc.",
    "TCA": "Trans Catalina Airlines",
    "26Q": "Albinati aviation Limited",
    "TXY": "Texas Airways",
    "AX": "Trans States Airlines",
    "NY": "New York Air Inc.",
    "BAC": "Business Aircraft Corp.",
    "HO": "Mid Pacific Airlines Inc.",
    "OTT": "Otter Air",
    "ECA": "Eagle Airlines",
    "ALE": "Air-Lift Associates Inc.",
    "ME": "Middle East Airlines S.A.L.",
    "GL": "Miami Air International",
    "K5": "Wings Of Alaska",
    "TIQ": "Tyrolean Jet Service",
    "AV": "Aerovias Nacl De Colombia",
    "LSQ": "Lineas Aereas Suramerican",
    "1FQ": "Alsek Air",
    "3SD": "Compagnie Aerienne Inter Regionale Express dba Air Antilles Express & Air Guyane",
    "QB": "Inter-Quebec",
    "CAM": "C & M Airlines",
    "WWI": "Wings West Airlines",
    "2EQ": "J&M Alaska Air Tours Inc. d/b/a Alaska Air Transit",
    "PA": "Pan American World Airways",
    "W3": "Arik Air International",
    "SMO": "Samoa Aviation Inc.",
    "2BQ": "Air Medical Ltd.",
    "HLQ": "Heavylift Cargo Airlines Lt",
    "MAX": "Maxair Inc.",
    "AE": "Air Europe Limited",
    "V9": "Eagle Airlines",
    "IRQ": "Interstate Airlines Inc.",
    "POA": "Potomac Air",
    "U7": "USA Jet Airlines Inc.",
    "1RQ": "Sun Air Express LLC dba Sun Air International",
    "7P": "Apa International Air S.A.",
    "ABH": "Air Bahia",
    "EVQ": "Aeroejecutivo S.A.",
    "SA": "South African Airways",
    "TB": "USAir Shuttle",
    "GCH": "Grand Canyon Helicopters",
    "TUL": "Tulsair Beechcraft Inc.",
    "NAT": "National Air",
    "SBA": "Saber Aviation Inc.",
    "AVA": "Air Vectors Airways",
    "SK": "Scandinavian Airlines Sys.",
    "VE": "Aerovias Venezolanas-Avensa",
    "ARP": "Airspur Helicopters Inc.",
    "RP": "Chautauqua Airlines Inc.",
    "CGL": "Viking International Airlines Inc.",
    "DQQ": "Caribwest Airways Ltd.",
    "RC": "Republic Airlines Inc.",
    "AAB": "Antilles Air Boats Inc.",
    "COT": "Southeastern Commuter",
    "TFZ": "Tri-State Airlines Inc.",
    "CAF": "California Seaboard",
    "3U": "Sichuan Airlines Co Ltd.",
    "LLA": "Lakeland Aviation",
    "WI": "Tradewinds Airlines",
    "CTA": "Century Airlines",
    "2DQ": "Aviation Partners of Boynton Beach LLC d/b/a Hummingbird Air",
    "CKI": "Inlet Airlines",
    "LEX": "L'Express",
    "RJ": "Alia-(The) Royal Jordanian",
    "BA": "British Airways Plc",
    "ICF": "Iowa City Flying Service",
    "2P": "Air Philippines Corp d/b/a Airphil Express Philippines Airlines",
    "GS": "Grant Aviation",
    "ELL": "Ellis Air Taxi Inc.",
    "SYM": "Skymaster",
    "SLZ": "Southeast Airlines Inc.",
    "FFQ": "Five Star Airlines",
    "PCA": "Piasa Commuter Airlines",
    "IOW": "Iowa Airways",
    "PLA": "Planes Inc.",
    "1YQ": "Air Charter Inc d/b/a Air Flamenco",
    "KOD": "Kodiak Airways Inc.",
    "NTQ": "National Aviation Consult.",
    "LM": "Alm Antillean Airlines",
    "QD": "Grand Airways Inc.",
    "WSK": "AAR Western Skyways",
    "JCQ": "Jet Connection Businessflight Ag",
    "GMA": "Green Mountain Airlines Ltd.",
    "SKB": "Smokey Bay Air Inc.",
    "SAH": "Sea Air Shuttle",
    "VIN": "Vale International Airlines",
    "CP": "Canadian Airlines International Ltd.",
    "UYQ": "Aerolineas Uruguayas S.A.",
    "GF": "Gulf Air Transport Inc.",
    "SEM": "Semo Aviation Inc.",
    "ASE": "Arctic Circle Air Service",
    "WOQ": "Winnport Logistics",
    "XF": "Vladivostok Air",
    "RYA": "Arctic Transportation",
    "CVQ": "Caraven S.A.",
    "UR": "Empire Airlines Inc.",
    "EA": "Eastern Air Lines Inc.",
    "0LQ": "Metropix UK LLP.",
    "LAR": "Laredo Air",
    "HJ": "Air Haiti S. A.",
    "IMP": "Imperial Airlines Inc.",
    "EXA": "Columbia Pacific Airlines",
    "XAL": "Challenge Air Transport Inc.",
    "TQA": "Venture Travel LLC d/b/a Taquan Air Service",
    "MS": "Egyptair",
    "ERI": "Erie Airways Inc.",
    "SPG": "Springdale Air",
    "NA": "North American Airlines",
    "PRD": "Paradise Island Airlines",
    "IR": "Iran National Airlines Corp",
    "SRA": "Star Aviation",
    "AFQ": "Aero B Venezuela C.A.",
    "KB": "Haiti Air",
    "XBW": "DHL Airways",
    "ATQ": "Aero Tranportes Panamenos",
    "PRM": "Prime Air Inc.",
    "XBV": "Nal Inc.",
    "WAC": "Air East Airlines",
    "MUA": "Manu'a Air Transport",
    "AMI": "American Inter-Island Inc.",
    "IAS": "Island Air Service",
    "CUS": "Custom Air Service",
    "LIQ": "Liat",
    "TRP": "Trans Pennsylvania Airlines",
    "RWG": "Air Rovers Inc.",
    "GE": "Lufthansa Cargo Airlines",
    "EIA": "East. Indiana Aviation Sale",
    "CCA": "Cityhop",
    "BDQ": "Aerotaxis De Aguascalientes S.A. De C.V.",
    "WRD": "Ward Air",
    "OZA": "Ozark Air Lines Inc.",
    "PDA": "Trans Southern Airways",
    "WG": "Sunwing Airlines Inc.",
    "1AQ": "Via Airlines d/b/a Charter Air Transport",
    "NKQ": "Norcanair",
    "SKI": "Sunbird Inc.",
    "BLQ": "Air Bvi Limited",
    "FX": "Federal Express Corporation",
    "BJQ": "Taxirey S.A. De C.V.",
    "PK": "Pakistan International Airlines",
    "DH": "Independence Air",
    "ANO": "Metro Air Northeast Vermont",
    "XAM": "Cohlmia Aviation",
    "EXQ": "Export Air Del Peru S.A.",
    "CS": "Continental Micronesia",
    "ARA": "Air Resorts Airlines",
    "AAA": "Associated Aviation Act.",
    "FH": "Frontier Horizon Inc.",
    "NVX": "Nevis Express",
    "BY": "Britannia Airways Ltd.",
    "WNQ": "Winair Inc.",
    "ORI": "Orion Air Inc.",
    "TWQ": "Air Transat",
    "ACI": "AAA-Action Air Carrier Inc.",
    "BFQ": "Buffalo Airways Inc.",
    "0FQ": "Maine Aviation Aircraft Charter LLC",
    "FLA": "Florida Air",
    "SPF": "Springfield Air Service",
    "EWA": "Rio Grande Air",
    "ERA": "Era Aviation",
    "25Q": "Mjet GmbH",
    "LEQ": "Le Point Air",
    "V8": "Iliamna Air Taxi",
    "XAH": "Hawaii Pacific Air",
    "ARB": "Air Caribe International",
    "SEB": "Seaborne Aviation",
    "RYQ": "Ryan International Airlines",
    "S3": "Santa Barbara Airlines C.A",
    "SAX": "Air Americana",
    "GX": "Air Ontario Limited",
    "TMA": "Trans Mo Airlines",
    "AVL": "Aviation Sales",
    "HEL": "Helitrans",
    "WRB": "40-Mile Air",
    "RHA": "Royal Hawaiian Airways Inc.",
    "IJ": "Air Liberte Aka Aom Minerve",
    "K7": "Arizona Express",
    "JCZ": "Rocky Mountain Airways Inc.",
    "H5": "Magadan Airlines",
    "ONQ": "Nunasi-Central Airlines Ltd.",
    "AP": "Aeromexpress",
    "AON": "Action Airlines",
    "EI": "Aer Lingus Plc",
    "BEY": "Beyer Aviation",
    "INQ": "Independent Air Inc.",
    "CK": "China Cargo Airline",
    "3M": "Silver Airways",
    "OGZ": "Flying Boat Inc.",
    "V5": "J.D.Valenciana De Aviation",
    "0TQ": "Corporatejets XXI",
    "ARM": "Airmarc Airlines Inc.",
    "BIQ": "Servicios Aeronauticos Z S.A. De C.V.",
    "9W": "Jet Airways",
    "PRH": "Promech",
    "WFS": "Wheeler Airlines",
    "BHQ": "Turks Air Ltd.",
    "CCO": "Chester County Aviation",
    "NSQ": "North Coast Air Services",
    "SAQ": "Southern Air Transport Inc.",
    "M7": "Aerotransportes Mas De Crga",
    "BRO": "Brower Airways Inc.",
    "CAV": "Air Virginia",
    "AFS": "Arcata Flying Service",
    "5B": "Bellair Inc.",
    "FGS": "Flagship Airlines Inc.",
    "XAS": "Klondike Air Inc.",
    "CLB": "Columbia Pacific Airlines",
    "BCA": "Baja Cortez Airlines",
    "AAZ": "Alaska Aeronautical Indust.",
    "IB": "Iberia Air Lines Of Spain",
    "WV": "Air Greco Inc. d/b/a Wings Air",
    "CTQ": "Custom Air Transport",
    "DM": "Maersk Air I/S",
    "XBH": "Profit Airlines Inc.",
    "BD": "British Midland Airways Ltd.",
    "0OQ": "Open Skies",
    "DIC": "Dickman Aviation Services",
    "LDM": "Lauda Motion GmbH",
    "ZE": "Eastar Jet Co Ltd.",
    "AAV": "Alpine Air",
    "AY": "Finnair Oy",
    "OG": "Air Guadeloupe",
    "GRO": "Isle Royale Seaplane Serv.",
    "07Q": "Flair Airlines Ltd.",
    "CCD": "Cascade Airways Inc.",
    "WLQ": "Worldwide Airlines Inc.",
    "VJT": "VistaJet Limited",
    "RSC": "Resort Commuter",
    "NEC": "Nor East Commuter Airlines",
    "AMQ": "Ameristar Air Cargo",
    "PFQ": "Asia Pacific",
    "WIL": "Will's Air",
    "RG": "Varig S. A.",
    "MVA": "Mississippi Valley Airlines",
    "LHA": "Havasu Airlines",
    "SSQ": "Superior Airways Limited",
    "MIN": "Minuteman Aviation Inc.",
    "ARR": "Arrowhead Airways Inc.",
    "STG": "Sedalia Marshall Boonvl Stg",
    "JW": "Arrow Air Inc.",
    "XAJ": "Central American International",
    "RIO": "Rio Airways Inc.",
    "SZQ": "Aerolineas El Salvador S A",
    "UXQ": "Air Europa",
    "PLQ": "Planet Airways",
    "ACJ": "Atlantic Coast Jet Inc.",
    "KEE": "Key Airlines",
    "ALQ": "Alberta Northern Airlines",
    "CAC": "Coleman Air Transport",
    "PPQ": "Propair",
    "4O": "ABC Aerolineas SA de CV dba Interjet",
    "WN": "Southwest Airlines Co.",
    "ADV": "Advantage Airlines",
    "AOI": "Trans New York",
    "ECI": "Eastern Carolina Aviation",
    "SHV": "Shavano Air Inc.",
    "BIR": "Birchwood Air Service",
    "8Q": "Baker Aviation Inc.",
    "UMQ": "Air Manila Inc.",
    "KWZ": "Crown Air",
    "TUR": "Turner Aire",
    "FRT": "Frontier Commuter",
    "ARD": "Airlift International",
    "COC": "Cochise Airlines Inc.",
    "C5": "Commutair Aka Champlain Enterprises Inc.",
    "0Q": "Flying Service N.V.",
    "FOR": "Ford-Aire Inc.",
    "INA": "Inland Empire Airlines Inc.",
    "FW": "Skybus Inc.",
    "QG": "Sky West Aviation Inc.",
    "1NQ": "JSC The 224th Flight Unit State Airlines",
    "AVS": "Aviation Services",
    "TCL": "Trans-Central Airlines Inc.",
    "CET": "Century Airlines",
    "DAU": "Dauphin Island Airways",
    "XG": "North American Airlines",
    "SO": "Swiss World Airways",
    "RB": "Syrian Arab Airlines",
    "CWQ": "Canadian Aviation Express",
    "SIM": "Simmons Airlines",
    "STA": "State Airlines Inc.",
    "URQ": "Aero Uruguay",
    "SNE": "Shawnee Airlines",
    "XAK": "Century Airlines Inc.",
    "NWQ": "N. W. Territorial Airways",
    "MAI": "The Maui Commuter",
    "2OQ": "Talofa Airways Limited",
    "HA": "Hawaiian Airlines Inc.",
    "2HQ": "Elite Airways LLC",
    "SNB": "Ccair",
    "BC": "Skymark Airlines Inc.",
    "APL": "Appalachian Flying Service",
    "SKL": "Bas Airlines",
    "AFE": "Air Florida Express",
    "LOS": "Aero Commuter",
    "BRW": "Barrow Air",
    "GBA": "Central States Airline",
    "SAC": "Sundorph Aeronautical Corp.",
    "WP": "Island Air Hawaii",
    "XBF": "WTC Airlines",
    "GAS": "General Aviation Inc.",
    "IPI": "Indo-Pacific International",
    "VIA": "Air St. Thomas",
    "RCA": "Mid-South Aviation Inc.",
    "PR": "Philippine Airlines Inc.",
    "MAG": "Magum Airlines",
    "TXA": "Texas National Airlines",
    "W4": "Mn Aviation Inc.",
    "KL": "Klm Royal Dutch Airlines",
    "RGQ": "Regency Air",
    "2TQ": "Trans Northern Airways d/b/a Air Unlimited Charter Services",
    "RRT": "Air Freight Express",
    "7S": "Arctic Transportation",
    "ADR": "Adirondack Airlines",
    "AJ": "Air Micronesia Inc.",
    "E9": "Boston-Maine Airways",
    "NI": "Lanica",
    "MT": "Thomas Cook Airlines Uk Ltd.",
    "XBQ": "Aeronaves De Puerto Rico",
    "9R": "Flagship Express Services",
    "ASP": "Asap Air Inc.",
    "OAS": "Olson Air Service",
    "FSA": "F.S. Air Service",
    "RAL": "Royal-Air Ltd.",
    "LAS": "Lake Union Air Service",
    "GHA": "Green Hills Aviation Ltd.",
    "POL": "Polar International",
    "NG": "Lauda Air Luftfahrt Ag",
    "NPT": "E. J. A. Newport Inc.",
    "MNA": "M & N Aviation",
    "CMI": "Comair Inc.",
    "TP": "Tap-Portuguese Airlines",
    "AS": "Alaska Airlines Inc.",
    "ET": "Ethiopian Airlines",
    "CZQ": "Aviation Concepts",
    "MPC": "Mid Pacific Air Corp.",
    "CXQ": "Casino Express",
    "LF": "CFM Inc d/b/a Contour Airlines",
    "5T": "Air America",
    "BES": "Aeroservices Executive",
    "MM": "Sociedad Aeronautica De Med",
    "CIQ": "A/S Conair",
    "ZY": "Atlantic Gulf Airlines",
    "JO": "Jalways Co. Ltd.",
    "VY": "Highland Express Airways",
    "ACA": "Alaska Central Airways Inc.",
    "SOA": "Mall Airways Inc.",
    "XBJ": "International Air Service",
    "BQ": "Aeromar C. Por A.",
    "JAM": "Sunbelt Airlines Inc.",
    "PNQ": "Panagra Airways",
    "TTM": "The Time Machine",
    "DO": "Compania Dominicana De Avia",
    "GAT": "Gulf Air Taxi",
    "ADQ": "Aeronaves Del Peru",
    "AVR": "Air Vermont Inc.",
    "VH": "Aeropostal Alas De Venezuel",
    "KAT": "Katmai Air",
    "CGQ": "Aerochago S.A.",
    "XCA": "Hawkins And Powers Aviation",
    "CAI": "Crawford Aviation Inc.",
    "SUX": "Sunair Express LLC",
    "OE": "Westair Airlines Inc.",
    "OV": "Aeromaritime",
    "5V": "Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo",
    "HBQ": "Harris Air Services",
    "CA": "Air China",
    "CCQ": "Capital Cargo International",
    "RSV": "Air-Serve",
    "FVA": "Skycraft Inc.",
    "POQ": "Polyot Airlines",
    "FRW": "Farwest Airlines",
    "MOQ": "Morningstar Air Express",
    "LV": "Linea Aeropostal Venezolana",
    "IPQ": "Aruba Cargo",
    "WM": "Windward Islands Airways",
    "AVG": "Airvantage",
    "VP": "Viacao Aerea Sao Paulo",
    "DY": "Norwegian Air Shuttle ASA",
    "SYQ": "Sun Country Airlines",
    "AHQ": "Air National",
    "SJQ": "Skycharter",
    "MES": "Mesaba Airlines",
    "ATX": "Air Carolina",
    "RAN": "Pan Am Express",
    "BFG": "Million Air",
    "EAQ": "Executive Airlines SL",
    "NEB": "New Born Wings Inc.",
    "HQ": "Business Express",
    "VSA": "VistaJet Luftfahrtunternehmen GmbH",
    "EE": "Eastern Airlines Group Inc.",
    "GW": "SkyGreece Airlines S A",
    "GSQ": "Global Supply System",
    "VAS": "Valley Air Services",
    "SUT": "Sunbelt",
    "H2": "City Bird",
    "IKQ": "Tradewinds Airways Ltd.",
    "OZ": "Asiana Airlines Inc.",
    "RI": "Airpac Inc.",
    "IGA": "Global Jet Austria GmbH",
    "GWA": "Great Western Aviation",
    "17": "Piedmont Airlines",
    "JX": "Southeast Airlines",
    "PUQ": "Aeropuma",
    "XAB": "Air Polynesia d/b/a DHL Cargo",
    "MCO": "Mid Continental Airlines In",
    "7B": "Krasair",
    "RES": "Resort Airlines Inc.",
    "BRQ": "Caledonian Airways",
    "23Q": "Songbird Airways Inc.",
    "1TQ": "Rhoades Aviation dba Transair",
    "FL": "Frontier Airlines Inc.",
    "COR": "Coral Air Inc.",
    "JIQ": "Jet Fleet Intl. Airlines",
    "0YQ": "Comlux Malta Ltd.",
    "EHA": "East Hampton Aire Inc.",
    "FC": "Fast Colombia SAS d/b/a Viva Colombia",
    "VIQ": "Volga-Dnepr Airlines",
    "1HQ": "International Jet Management GmbH",
    "5F": "Arctic Circle Air Service",
    "PMT": "Pilgrim Aviation & Airlines",
    "SFI": "Stahmannfarms Inc.",
    "EMP": "Empire Airlines Inc.",
    "RZZ": "Aeromech Inc.",
    "GCA": "Golden Carriage Aire",
    "DPA": "Desert Pacific Airways",
    "XAF": "Astro-Wing Airlines Inc.",
    "SFO": "Sfo Helicopter Airlines Inc.",
    "FNQ": "Fine Airlines Inc.",
    "AMT": "American Air Transport",
    "TVL": "Travelair",
    "FP": "TAG Aviation S.A.",
    "TFQ": "Trans International Airlines Inc.",
    "RMH": "Rocky Mountain Helicopters",
    "J6": "Larrys Flying Service",
    "BXQ": "Spantax S. A.",
    "EFA": "Executive Four Winds",
    "JI": "Jade Cargo International",
    "EW": "Eurowings GmbH",
    "SIA": "Silver State Airlines",
    "B8": "Caribbean Airline Company",
    "PAT": "Panorama Air Tours",
    "OOZ": "Sun Aire Lines",
    "CUQ": "Caicos Caribbean Airways",
    "GBQ": "G5 Executive Ag",
    "ANE": "Pacific Wings Airlines",
    "6A": "Aviacsa Airlines",
    "Q4": "Master Top Linhas Aereas Ltda.",
    "BSA": "Big Sky Airlines Inc.",
    "EM": "Empire Airlines Inc.",
    "WA": "Worldwide Airlines Services",
    "PET": "Petro Aviation Corp.",
    "HMZ": "Long Island Airlines",
    "FB": "Translift Airways Limited",
    "ATA": "Atlantic Southeast Airlines",
    "HNA": "Piedmont Airlines",
    "29Q": "Erickson Helicopters",
    "SM": "Sunworld International Airlines",
    "KE": "Korean Air Lines Co. Ltd.",
    "ARZ": "Arizona Airways",
    "CSL": "Central States Air Lines",
    "HFS": "Hensley Flying Service Inc.",
    "0UQ": "Comlux Malta Ltd.",
    "XBC": "Jet East Inc.",
    "ZA": "Accessair Holdings",
    "W9": "Eastwind Airlines Inc.",
    "ACG": "Air Cargo Express Inc.",
    "G9": "Grant Aviation",
    "JKQ": "Express One International Inc.",
    "AIK": "Air Ketchum Idaho Inc.",
    "SST": "Seaplane Shuttle Transport",
    "VCQ": "Victory Air Transport Inc.",
    "CW": "Air Marshall Islands Inc.",
    "AIY": "Alliance Air",
    "HQQ": "Harlequin Air Corporation",
    "AIN": "Air Indiana",
    "LXQ": "Translux Intl Airlines",
    "JXQ": "Allarco Developments Ltd.",
    "LJ": "Jin Air Co Ltd.",
    "CMQ": "Servicio De Carga Aerea Sa",
    "FAC": "Falcon Airways Inc.",
    "XBX": "Icb International Airlines",
    "PRO": "Sundance Airlines",
    "EH": "Saeta Airlines",
    "PER": "Air Pennsylvania",
    "ATH": "Air Southeast",
    "KKQ": "Transmeridian Air Cargo Ltd.",
    "CRP": "Corporate Air",
    "HP": "America West Airlines Inc.",
    "VAG": "Vagabond Aviation Inc.",
    "PBA": "Provincetown Boston",
    "DPI": "Desert Pacific Airlines Inc.",
    "MTA": "Arkansas Traveler Airline",
    "XAE": "Amerford Airways Inc.",
    "BKR": "Baker Aviation Inc.",
    "MZ": "P.N. Merpati Nusantara Air.",
    "XPE": "Amira Air GmbH",
    "R3": "Air Company Yakutia",
    "4N": "Air North",
    "USA": "Air U.S.",
    "MSQ": "Martinair Holland N.V.",
    "MAA": "Maui Airlines",
    "OB": "Oasis International Airlines S.A.",
    "UO": "Hong Kong Express Airways Limited",
    "QT": "Pacific Interstate Airlines",
    "OS": "Austrian Airlines",
    "MRR": "Merrimack Aviation Inc.",
    "2JQ": "Delux Public Charter LLC",
    "OJ": "Fly Jamaica Airways Limited",
    "PHX": "Phoenix Airlines",
    "HRQ": "Tar Airlines",
    "JZ": "Japan Air Charter Co. Ltd.",
    "3K": "Tatonduk Outfitters Limited d/b/a Tatonduk Flying Service",
    "XY": "Munz Northern Airlines Inc.",
    "9V": "Avior Airlines C.A.",
    "6B": "Britannia Airways A.B.",
    "9M": "Central Mountain Air",
    "XDA": "Pacific Air Express Inc.",
    "BUH": "Business Helicopters",
    "XBI": "CF Air Freight",
    "AVC": "Av Center Inc.",
    "MW": "Mokulele Flight Services Inc.",
    "AA": "American Airlines Inc.",
    "MMH": "Ocean Airways Inc.",
    "QTQ": "Aer Turas Teoranta",
    "US": "US Airways Inc.",
    "0GQ": "Inter Island Airways d/b/a Inter Island Air",
    "PRP": "Propheter Aviation",
    "EEX": "Exec Express",
    "AQQ": "Air Charter",
    "7Q": "Pan American World Airways Dominicana",
    "PM": "Prescott Support Company Inc.",
    "H7": "Venture Travel LLC d/b/a Taquan Air Service",
    "SFQ": "Southern Frontier Air Trans",
    "AIG": "Airgo Inc.",
    "RY": "Redcoat Air Cargo Limited",
    "LAB": "L.A.B. Flying Service Inc.",
    "AJQ": "Aerodynamics Inc. d/b/a SkyValue d/b/a SkyValue Airways",
    "MX": "Compania Mexicana De Aviaci",
    "RIV": "Riverside Air Service",
    "VEZ": "Valdez Airlines",
    "SN": "Sabena Belgian World Air.",
    "AGA": "Air Cargo America Inc.",
    "FCA": "Southern Airlines Inc.",
    "LCQ": "Latcr",
    "RNQ": "Airtours International Airways",
    "OP": "Pan American World Airways",
    "AEF": "Aero Freight",
    "ASH": "Air South",
    "ALD": "Allied Airlines",
    "LRQ": "Air Liberte",
    "NHA": "Newair Flight Inc.",
    "WR": "WestJet Encore Ltd.",
    "PRR": "Pro Air Services",
    "ZUQ": "Zuliana De Aviacion",
    "0MQ": "Multi-Aero Inc. d/b/a Air Choice One",
    "REP": "Republic Airlines",
    "BNQ": "BNJ Charter Company",
    "9T": "TravelspanGT Inc. S.A.",
    "NER": "Northeast Express Regional",
    "JJ": "Transportes Aeros Meridiona",
    "A2": "Cielos De Peru",
    "KFS": "King Flying Service",
    "QQ": "Reno Air Inc.",
    "LBQ": "Millon Air Inc.",
    "TCQ": "Trans Continental Airlines",
    "WIA": "Wisc Air",
    "ASQ": "Aerosur",
    "XAN": "Conner Air Lines Inc.",
    "KM": "Air Malta",
    "SEG": "Seagull Air Service",
    "9S": "Southern Air Inc.",
    "CMB": "Combs Airways Inc.",
    "NEX": "Northeast Express Regional",
    "DIR": "Northern Star",
    "OC": "Air California Inc.",
    "WT": "Nigeria Airways Ltd.",
    "QOZ": "Bar Harbor Airways",
    "2R": "Regal Air",
    "SNV": "Sierra Nevada Airways",
    "SIQ": "Scanair",
    "TGO": "Trans Air Cargo Inc.",
    "MST": "Midwest Aviation",
    "XJ": "Mesaba Airlines",
    "VER": "Britt Airlines Inc.",
    "W8": "Cargojet Airways Ltd.",
    "LH": "Lufthansa German Airlines",
    "KX": "Cayman Airways Limited",
    "AM": "Aeromexico",
    "CVA": "Catalina-Vegas Airlines",
    "OFF": "Offshore Logistics",
    "AIE": "Air Express Inc.",
    "CRA": "Commuter Airlines",
    "DHQ": "DHL Aero Expresso",
    "CBA": "Carriba Air Inc.",
    "DWN": "Dawn Air",
    "OIZ": "Corporate Air Inc.",
    "CHT": "Charter One",
    "BE": "Braniff International Airlines Inc.",
    "KAI": "Knight Airlines Inc.",
    "NFA": "National Florida Airlines",
    "PV": "Eastern Provincial Airways",
    "SPQ": "Sun Pacific International",
    "CEN": "Cen-Tex Airlines Inc.",
    "7G": "Bellair Inc.",
    "COM": "Commutair",
    "SJA": "San Juan Airlines Inc.",
    "XAG": "Ball Brothers Inc.",
    "MRQ": "National Air Cargo Group Inc. d/b/a Murray Air",
    "STF": "Trans East International",
    "SU": "Aeroflot Russian Airlines",
    "FCQ": "Falcon Air Express",
    "ALK": "Air Link Airways",
    "6Y": "Nicaraguense De Aviacion Sa",
    "10Q": "Swiss Air Ambulance",
    "VL": "Mid-South Aviation Inc.",
    "CAQ": "Challenge Air Luftverkehrs GmbH",
    "MVQ": "Aom Minerve S.A.",
    "RJS": "Michigan Airways Inc.",
    "NPA": "North Pacific Airlines Inc.",
    "OA": "Olympic Airways",
    "GU": "Aviateca",
    "GR": "Gemini Air Cargo Airways",
    "OI": "Prestige Airways",
    "MTX": "Mountain Air Express",
    "SLO": "Slocum Air Inc.",
    "CHL": "Channel Flying Inc.",
    "SKS": "Silver Kris Services Ltd.",
    "TAC": "Air Colorado",
    "LP": "Lan Peru Airlines",
    "ACW": "Transwest Air Express",
    "ZQ": "Caribbean Sun Airlines",
    "OCR": "Ocean Reef Airways Inc.",
    "GLA": "Great Lakes Aviation Ltd.",
    "1JQ": "Exec Direct Aviation Services Limited",
    "ANT": "Air North/Nenana",
    "MIW": "Airborne Express Inc.",
    "0BQ": "DCA",
    "JD": "Beijing Capital Airlines",
    "KXQ": "Cayman Airways Limited",
    "INL": "Inland Aviation Services",
    "PIQ": "Pacific International Airlines",
    "PTQ": "Flight International",
    "NWS": "Northwest Seaplanes",
    "SLR": "Salair",
    "SAS": "Air Cortez International",
    "FAA": "Falwell Aviation Inc.",
    "JAG": "JetAlliance Flugbetriebs d/b/a JAF Airservice",
    "LSZ": "Alaska Island Air Inc.",
    "ZKQ": "Zantop International",
    "2T": "Canada 3000 Airlines Ltd.",
    "CQI": "Conquest Airline Corp.",
    "GA": "P.T. Garuda Indonesian Arwy",
    "WD": "Halisa Air",
    "SEA": "SkyWest Airlines Inc.",
    "S4": "Sata Internacional",
    "BEN": "Bennington Aviation Inc.",
    "PAI": "Permian Airways Inc.",
    "HSZ": "Scenic Airlines Inc.",
    "NTH": "Northaire",
    "MPA": "Mid Pacific Airlines Inc.",
    "EAS": "Eastern Caribbean Airways",
    "THO": "Thorson Aviation",
    "SNC": "Gelco Courier Services Inc.",
    "8L": "Servicio Aereo Leo Lopez",
    "MTR": "Metroflight Airlines",
    "IW": "Air Liberte Aka Aom Minerve",
    "ASN": "Air Casino",
    "IA": "Iraqi Airways",
    "4E": "Tanana Air Service",
    "1PQ": "Makani Kai Air Charters",
    "YUT": "Yute Air Aka Flight Alaska",
    "VW": "Transportes Aeromar S.A de C.V",
    "0ZQ": "Air Excursions LLC",
    "HCQ": "Av Atlantic",
    "GUL": "Gull Air Inc.",
    "QWE": "Qwest Commuter",
    "SV": "Saudi Arabian Airlines Corp",
    "GFQ": "Gulf And Caribbean Cargo",
    "RTQ": "Aerotour Dominicano Cxa",
    "AI": "National Aviation Company of India Limited d/b/a Air India",
    "ERQ": "Aero Trades",
    "APC": "Air Puerto Rico Airlines",
    "HEU": "Heussler Air Service Corp",
    "GPA": "GP Express Airlines",
    "SBQ": "Skyjet S.A.",
    "ACD": "Academy Airlines",
    "RVQ": "Reeve Air Alaska LLC",
    "RDW": "Redwing Airways",
    "R2": "Orenburg Airlines",
    "4T": "Belair Airlines Ltd.",
    "WES": "Western Star Airlines Inc.",
    "NFQ": "North Cariboo Flying Serv.",
    "PRN": "Puerto Rico Intl Airlines",
    "FOS": "Foster Aviation",
    "7L": "Silk Way West Airlines",
    "SSS": "Sierra Express Inc.",
    "NGL": "Northern Eagle Airways Inc.",
    "ICQ": "Iscargo Hf",
    "TR": "Transbrasil S.A.",
    "21Q": "Corporate Flight Management Inc.",
    "P3": "Cargologicair Limited",
    "TIE": "Trans International Express",
    "0JQ": "Vision Airlines",
    "OMQ": "Quassar De Mexico",
    "STR": "Star Aviation Corporation",
    "NBQ": "Sterling Airways A/S",
    "SMC": "Stopher Mechanical Inc.",
    "LG": "Luxair",
    "RID": "Indiana Airways Inc.",
    "NCP": "Colgan Air",
    "CHA": "Chautauqua Airlines Inc.",
    "PVA": "Precision Valley Aviation",
    "OH": "PSA Airlines Inc.",
    "MMQ": "Miami Air International",
    "PS": "Pacific Southwest Airlines",
    "PHR": "Pinehurst Airlines Inc.",
    "BAN": "Bangor International Air",
    "LA": "Lan-Chile Airlines",
    "HY": "Uzbekistan Airways",
    "LAN": "Lancer Aviation Inc.",
    "JCM": "Air Chico",
    "ZO": "Florida Express Inc.",
    "PE": "People Express Airlines Inc.",
    "ACH": "Island Airlines Hawaii Inc.",
    "AWA": "Air West Airlines",
    "EOQ": "Aeroservicios Ecuatorianos",
    "RMV": "Ram Aviation",
    "TXQ": "British Caribbean Airways",
    "CJ": "Colgan Airways Inc.",
    "A0": "Elysair d/b/a L'Avion",
    "SOL": "Soonair Lines Inc.",
    "VV": "Challenge Air International Inc.",
    "GST": "Golden State Airlines",
    "USQ": "USA 3000 Airlines",
    "TTD": "Tatonduk Outfitters Limited d/b/a Tatonduk Flying Service",
    "BR": "Cal Air International Ltd.",
    "BAQ": "Aero Rentas De Coahuila S.A. De C.V.",
    "EJQ": "Aeroejecutivos C.A.",
    "FLM": "Flamenco Airways Inc.",
    "G4": "Allegiant Air",
    "XDC": "Hemisphere Air Charter",
    "S6": "Mountain Bird/Salmon Air",
    "YBQ": "Yellow Bird Air",
    "LO": "Polskie Linie Lotnicze",
    "EGC": "Eagle Canyon Airlines d/b/a Scenic Airlines",
    "MHO": "Mahalo Air",
    "OQ": "Royale Airlines Inc.",
    "OHA": "Omaha Aviation",
    "MHK": "Mohawk Airlines",
    "FS": "Serv De Trans Aereos Fuegui",
    "2K": "Aerolineas Galapagos S A Aerogal",
    "QF": "Qantas Airways Ltd.",
    "AOQ": "Aerovias S.A.",
    "COL": "Presidential Express",
    "ZYZ": "Skyway Aviation Inc.",
    "ACT": "Air Central Inc.",
    "REQ": "Renown Aviation",
    "5D": "Aerolitoral",
    "MNZ": "Cumberland Airlines",
    "NJ": "Vanguard Airlines Inc.",
    "SNK": "Spernak Airways Inc.",
    "PW": "Pacific Western Airlines",
    "22Q": "Gem Air LLC",
    "EAI": "Executive Aviation Inc.",
    "GDW": "Golden West Airlines Inc.",
    "LS": "Jet2.com",
    "2Z": "Air Comet S.A.",
    "BAY": "Burlington Aeroplane Co.",
    "BMT": "Bremerton Aviation Inc.",
    "PIA": "Pacific Island Airways",
    "VQ": "Vintage Props & Jets Inc.",
    "TAQ": "Taquan Air Service",
    "HB": "Air Club International",
    "AVZ": "Southern Jersey Airways",
    "PKQ": "Skyworld Airlines Inc.",
    "AEX": "Air Excursions LLC",
    "SXP": "Sierra Expressway",
    "TZQ": "Air 2000 Limited",
    "ARO": "Air Oregon",
    "CSM": "Chisum Flying Service",
    "KZ": "Nippon Cargo Airlines",
    "NW": "Northwest Airlines Inc.",
    "T9": "TransMeridian Airlines",
    "SEQ": "Sky Service F.B.O.",
    "X9": "Omni Air Express",
    "20Q": "Orange Air",
    "XDD": "International Parcel Express Inc.",
    "ITQ": "Interamericana De Aviacion",
    "GLW": "Golden West Airlines Co.",
    "STL": "Westair Airlines Inc.",
    "CSA": "Casino Airlines",
    "1I": "Sky Trek International Airlines",
    "8E": "Bering Air Inc.",
    "KLQ": "Kalitta Charters II",
    "T3": "Tristar Airlines Inc.",
    "ASI": "Alpine Air Services Inc.",
    "MDQ": "Aerotransportes Mas De Crga",
    "IPS": "Island Express",
    "RDR": "Rader Aviation",
    "HK": "Time Air Sweden Ab",
    "PNA": "Peninsula Airways Inc.",
    "TAT": "Talarik Creek Air Taxi",
    "NB": "Sterling Cargo",
    "XDH": "Kitty Hawk Air Cargo",
    "GD": "Transp. Aereos Ejecutivos",
    "ASR": "Astor Air",
    "MEX": "Metro Express 11",
    "C2": "Challenge Air Cargo Inc.",
    "CSK": "Catskill Airways Inc.",
    "GY": "Guyana Airways Corporation",
    "CTH": "Cothron Aviation",
    "AC": "Air Canada",
    "SEP": "Southern Express Airways",
    "CTR": "Chartair",
    "1DQ": "Island Airlines LLC",
    "CHO": "Choi Aviation Inc.",
    "BCQ": "Bradley Air Services Ltd.",
    "HX": "Hong Kong Airlines Limited",
    "SNA": "Aviation Associates",
    "MAC": "Mackey International Inc.",
    "NAS": "Nasville Eagle",
    "FJ": "Air Pacific Ltd.",
    "OW": "Executive Airlines",
    "YM": "Royal West Airlines",
    "LUQ": "Lineas Aereas La-Tur Sa",
    "SCT": "Skyline Airlines",
    "HVQ": "Transavia Holland B. V.",
    "14Q": "London Air Services Limited",
    "U2": "UFS Inc.",
    "EBQ": "Execaire Aviation Ltd.",
    "M3": "ABSA-Aerolinhas Brasileiras",
    "NUQ": "Air Niugini",
    "FAQ": "Fast Air Carrier Ltd.",
    "OO": "SkyWest Airlines Inc.",
    "ABX": "ABX Air Inc",
    "TIS": "Skyfreight",
    "AKQ": "Airmark Airlines Inc.",
    "HET": "Helitac Aviation",
    "BYA": "Bay Air",
    "SWA": "Sunwest Airlines",
    "GRD": "Grand Canyon Airlines",
    "KN": "Morris Air Corporation",
    "BX": "Air Busan",
    "1WQ": "Ultimate JetCharters LLC dba Ultimate Air Shuttle",
    "XAI": "Burlington Northern Inc.",
    "TZ": "American Trans Air Inc.",
    "TRI": "Great Plains Airlines Inc.",
    "5J": "Private Jet Expeditions",
    "NAC": "National Air Commuter Inc.",
    "UTQ": "Universal Airlines Inc.",
    "CB": "Air One Inc.",
    "JK": "Spanair S.A.",
    "5G": "Skyservice Airlines Inc.",
    "XBP": "Circle Airfreight Corp.",
    "SQ": "Singapore Airlines Ltd.",
    "DFQ": "Condor Flugdienst",
    "2RQ": "Luxaviation S A",
    "6U": "Air Ukraine",
    "FF": "Tower Air Inc.",
    "FQ": "Air Aruba",
    "DE": "Condor Flugdienst",
    "EP": "All Star Airlines Inc.",
    "ERO": "Empire Aero Service",
    "CHS": "Christman Air System",
    "BM": "Belize Air International Ltd.",
    "RAY": "Royale Airlines Inc.",
    "2M": "Midway Express Airlines",
    "GIQ": "Global International Airways Corp.",
    "4H": "Belize Trans Air",
    "ABI": "Airbama Incorporated",
    "ROA": "Royal West Airways Inc.",
    "DSA": "Desert Sun Airlines",
    "1EQ": "KaiserAir Inc.",
    "CX": "Cathay Pacific Airways Ltd.",
    "9J": "Pacific Island Aviation",
    "EGL": "Eagle Commuter Airlines Inc.",
    "SKW": "Skyway Airlines",
    "PBQ": "Privatair",
    "GFC": "Gulf Flite Center",
    "EME": "Metro Express",
    "APY": "Air Polynesia Inc.",
    "PL": "Aero Peru",
    "1QQ": "City Wings Inc dba Seaflight",
    "CLD": "Hawaii Pacific Helicopters",
    "CPE": "Cape Air",
    "XBM": "Phh Air Inc.",
    "SFS": "Sierra Flite Service Inc.",
    "SCN": "Scott Aviation",
    "JR": "Aero California",
    "ZFZ": "Mcphillips Flying Service",
    "06Q": "Master Top Linhas Aereas Ltd.",
    "L7": "Lan Colombia",
    "KR": "Kar-Air Oy",
    "XBL": "Interstate Airlines Inc.",
    "VIG": "Viking Express",
    "SVL": "Sun Valley Airlines",
    "D7": "Air Asia X Berhad dba Airasia X",
    "UH": "US Helicopter Corporation",
    "4S": "Sol Air",
    "1SQ": "Star Marianas Air Inc.",
    "4Y": "Yute Air Aka Flight Alaska",
    "J7": "Valujet Airlines Inc.",
    "1BQ": "Dynamic Airways LLC",
    "Q7": "SkyBahamas Airlines Ltd.",
    "UC": "Ladeco",
    "DRQ": "Apa International Air S.A.",
    "FAR": "Federal Armored Service Inc.",
    "AFA": "American Flag Airlines Inc.",
    "AST": "Astro Airways",
    "TAL": "Tejas Airlines Inc.",
    "TQQ": "Taca Peru",
    "XPA": "Express Air d/b/a Sunrise",
    "HU": "Hainan Airlines Company Limited",
    "GCQ": "General Air Cargo",
    "CV": "Cargolux Airlines International S.A",
    "HEP": "Hub Express",
    "BF": "Alaska International Air",
    "XAO": "Dallas Flight Center",
    "ATO": "Pacific National Airways",
    "2WQ": "Paklook Air Inc d/b/a/ Airlift Alaska",
    "W7": "Western Pacific Airlines",
    "PLZ": "Polar Airways Inc.",
    "STQ": "Skycraft Air Transport Inc.",
    "ATT": "Aerotransit Inc.",
    "AL": "Skyway Airlines",
    "SVA": "Servant Air Inc.",
    "ARQ": "Aerovias Colombianas Arca",
    "SY": "Sun Country Airlines",
    "0VQ": "Ocean Sky",
    "BHO": "Bighorn Airways Inc.",
    "MG": "MGM Grand Air Inc.",
    "PJQ": "Private Jet Expeditions",
    "SR": "Swissair Transport Co. Ltd.",
    "G7": "GoJet Airlines LLC d/b/a United Express",
    "Z3": "PM Air LLC",
    "NZ": "Air New Zealand",
    "XAU": "Flight Line Inc.",
    "PO": "Polar Air Cargo Airways",
    "MIY": "Midway Aviation Inc.",
    "5L": "Aerosur",
    "16": "PSA Airlines Inc.",
    "0RQ": "TAG Aviation Espana S.L.",
    "PDQ": "Antigua Paradise Airways",
    "F9": "Frontier Airlines Inc.",
    "ATD": "Atlantic Coast Airlines",
    "4R": "Regent Air Corporation",
    "ROS": "Great Western Airlines Inc.",
    "CEA": "Corporate Airlines",
    "4M": "LAN Argentina",
    "AEO": "Aero Coach",
    "AR": "Aerolineas Argentinas",
    "8I": "Inselair Aruba NV",
    "TRQ": "Transwede Airways Ab",
    "SKG": "Skagway Air Service",
    "DOQ": "Aerolineas Dominicanas S A",
    "GG": "Grenada Airways Ltd.",
    "TS": "Air Transat",
    "N5": "Nations Air Express Inc.",
    "12Q": "Unijet",
    "TRR": "Territorial Airlines",
    "LT": "Luftransport-Unternehmen",
    "CDQ": "Kitty Hawk International",
    "NAQ": "Nationair",
    "VX": "Aces Airlines",
    "MC": "Transtar Airlines Corp.",
    "DUL": "Dulles Express",
    "BRK": "Barken International",
    "TAS": "Yosemite Airlines Inc.",
    "DOL": "Dolphin Airways Inc.",
    "YB": "Trans Continental Airlines",
    "CRB": "Caribair",
    "CRO": "Crown Airways Inc.",
    "SAJ": "Sajen Air Inc.",
    "EVA": "Evanston Aviation",
    "FFS": "Frontier Flying Service",
    "ECL": "Eclipse Airlines",
    "FTI": "Southern Airways",
    "ANM": "Airways Of New Mexico Inc.",
    "BEQ": "Air Belgium",
    "ST": "Belize Airways Limited",
    "AAP": "Armstrong Air Service Inc.",
    "ADB": "Antonov Company",
    "ALT": "Altus Airlines",
    "BAA": "Aero International Airlines",
    "ZP": "Air St. Thomas",
    "CF": "Compan. De Aviacion Faucett",
    "RSQ": "Aerotransportes Entre Rios",
    "XAW": "Northern Air Cargo Inc.",
    "CPT": "Capitol Air",
    "IXQ": "Inair",
    "CPC": "Coastal Plains Commuter Inc.",
    "3Z": "Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo",
    "KO": "Alaska Central Express",
    "WGQ": "Gateway Aviation Limited",
    "ARI": "Arizona Aero Corp.",
    "BRT": "Britt Airways Inc.",
    "Y8": "Yangtze River Express Airlines Company",
    "2KQ": "Longtail Aviation Ltd.",
    "IEX": "Island Air Express",
    "CHF": "Hammonds Commuter Air Serv.",
    "KAH": "Kenmore Air Harbor",
    "NVQ": "Novair International Airways Ltd.",
    "HNS": "Haines Airways",
    "CRV": "Acropolis Aviation Ltd.",
    "TSQ": "TPI International Airways",
    "GRT": "Grant Aviation",
    "SBN": "Suburban Airlines",
    "XBY": "Wrangler Aviation Inc.",
    "LAH": "La Helicopter",
    "TTQ": "Canada 3000 Airlines Ltd.",
    "L4": "Lynx Aviation d/b/a Frontier Airlines",
    "M6": "Amerijet International",
    "3C": "Regions Air Inc.",
    "BEA": "Business Express Airlines",
    "SDQ": "St. Lucia Airways Limited",
    "OMH": "Omniflight Helicopters",
    "WDQ": "Wardair Canada Inc.",
    "JM": "Air Jamaica Limited",
    "LW": "Pacific Wings Airlines",
    "PAQ": "Patriot Airlines Inc.",
    "AZQ": "Anglo Airlines Ltd.",
    "MAS": "Mesa Airlines Inc.",
    "MB": "Samoa Airlines Inc.",
    "SHA": "Shuttle America Corp.",
    "CZ": "China Southern Airlines",
    "CO": "Continental Air Lines Inc.",
    "FT": "Flying Tiger Line Inc.",
    "LC": "Legend Airlines",
    "AZ": "Alitalia-Linee Aeree Italia",
    "AIC": "Air Caribbean",
    "SLA": "Mountain Bird/Salmon Air",
    "AVI": "Aero Virgin Islands Corp.",
    "E7": "Estafeta Carga Aereas",
    "V4": "Vensecar International",
    "CC": "Air Atlanta Inc.",
    "CEQ": "All Canada Express",
    "ALX": "Atlanta Express",
    "2E": "Smokey Bay Air Inc.",
    "SOE": "Sky One Express",
    "CLF": "California Air Shuttle",
    "LNQ": "Aerolineas Latinas",
    "EXR": "Executive Transport",
    "XYZ": "Airpac Inc.",
    "NAP": "Npa Inc.",
    "LGQ": "Lineas Aereas Allegro",
    "PNM": "Panama Aviation",
    "0QQ": "TAG Aviation",
    "AAE": "AAA Airlines",
    "EEZ": "Eagle Aviation Inc.",
    "OAK": "Harbor Airlines Inc.",
    "MAQ": "Millardair Limited",
    "APE": "Air Cape",
    "NC": "Northern Air Cargo Inc.",
    "HOR": "Iowa Airlines",
    "XAY": "Pat Air",
    "DEC": "Decatur Aviation",
    "N7": "National Airlines",
    "6C": "Cape Smythe Air Service",
    "EXT": "Executive Air Charter",
    "XV": "Presidential Airways Inc.",
    "5C": "C.A.L Cargo Airlines",
    "CPA": "Capitol Air Lines",
    "AD": "Azul Linhas Aereas Brazileiras S A",
    "XPQ": "International Cargo Xpress",
    "MJ": "Lapa-Lineas Aereas Privadas",
    "WEQ": "Aero-Services-Corporate",
    "OMN": "Omni Pacific Airline",
    "WGL": "Wrangell Air Service",
    "OF": "Air Finland Ltd.",
    "AF": "Compagnie Natl Air France",
    "H6": "Hageland Aviation Service",
    "PU": "Primeras Lineas Uruguays For International",
    "WCA": "Walker's International",
    "NOQ": "Novair Airlines Ab",
    "HOL": "Holiday Airlines Inc.",
    "RIC": "Richardson Aviation",
    "VLY": "Valley Airlines",
    "Y4": "Concesionaria Vuela Compania De Aviacion SA de CV",
    "FRA": "Freedom Air",
    "0HQ": "Polar Airlines de Mexico d/b/a Nova Air",
    "YR": "Scenic Airlines Inc. d/b/a Scenic Airlines",
    "JU": "Air Serbia",
    "MAR": "Marshall's Air Inc.",
    "KW": "Carnival Air Lines Inc.",
    "SWT": "Swift Aire Lines Inc.",
    "LX": "Swiss International Airlines",
    "A4": "Southern Wind Airlines",
    "VOQ": "Avalon Aviation Ltd.",
    "EZ": "Evergreen International Inc.",
    "EKA": "Air Pacific Inc.",
    "KP": "Kiwi International",
    "09Q": "Swift Air LLC",
    "EAT": "Eastman Airways Inc.",
    "VEE": "PSA Airlines Inc.",
    "7N": "Inland Aviation Services",
    "7H": "Era Aviation",
    "4EQ": "Tanana Air Service",
    "8D": "Dynamic Aviation Inc. d/b/a Beacon",
    "TNQ": "Emery Worldwide Airlines",
    "REX": "Express Airlines Inc.",
    "7M": "Aeromonterrey S.A.",
    "MUQ": "Aerolineas Mundo",
    "ALL": "All Seasons Air Pacific",
    "OK": "Czech Airlines",
    "PN": "Pan American Airways Corp.",
    "BAT": "West Penn Commuter",
    "E72": "European Aviation Air Charter",
    "1LQ": "Bertelsmann Aviation GmbH",
    "PRA": "Princeton Aviation Corp",
    "2LQ": "Tropic Ocean Airways LLC",
    "7J": "Skagway Air Service",
    "D8": "Norwegian Air International Ltd.",
    "ICH": "Island Air Charters",
    "WSU": "Mission Air",
    "AEC": "Astec Air East Inc.",
    "PMA": "Pacific Missionary Aviation",
    "AEQ": "Air Caravane Inc.",
    "XBR": "Allstates Air Cargo Inc.",
    "WLB": "Wilburs Inc.",
    "1XQ": "Dassault Falcon Service",
    "ACL": "Check-Air Inc.",
    "7I": "Insel Air International B V",
    "FDQ": "Great American Airways",
    "RU": "Britt Airways Inc.",
    "YV": "Mesa Airlines Inc.",
    "AIT": "Airways International",
    "CGO": "Chicago Air Taxi",
    "LU": "Air Atlantic Dominicana",
    "NQ": "Air Japan Co",
    "CHD": "Chandler Flyer",
    "2F": "Frontier Flying Service",
    "WO": "World Airways Inc.",
    "JN": "Excel Airways",
    "VI": "Volga-Dnepr Airlines",
    "CYQ": "Corse Air International",
    "VAQ": "Vacationair",
    "RK": "Air Afrique",
    "APH": "Alpha Air",
    "NH": "All Nippon Airways Co.",
    "CPQ": "Capitol Air Express Inc.",
    "CMT": "Commutair Aka Champlain Enterprises Inc.",
    "RS": "Sky Regional Airlines Inc.",
    "EGA": "Eagle Airline",
    "MF": "Xiamen Airlines Co. Ltd.",
    "ED": "Andes",
    "PSA": "P.S. Air Freight Inc.",
    "XAT": "Michigan Peninsula Airways",
    "DHL": "DHL Airlines Inc.",
    "C6": "Canjet Airlines",
    "TXE": "Trans Air",
    "8C": "Air Transport International",
    "A7": "Air 21",
    "NEV": "Nevada Airlines",
    "DC": "Caribbean Air Cargo Co Ltd.",
    "HRZ": "Allegheny Airlines",
    "PAV": "Pacific Island Aviation",
    "AIA": "All Island Air",
    "TNS": "Transtate Aviation",
    "SMQ": "Serv. Aerolineas Mexicanas",
    "PP": "Jet Aviation Business Jets AG",
    "GQ": "Big Sky Airlines Inc.",
    "7F": "First Air",
    "PD": "Porter Airlines Inc.",
    "ATS": "Atlantis Airlines Inc.",
    "DST": "Desert Airlines",
    "RW": "Republic Airlines",
    "BHK": "Blackhawk Airways Inc.",
    "SPR": "Sportsman Flying Service",
    "SLQ": "Sky King Inc.",
    "GH": "Ghana Airways Corporation",
    "KU": "Kuwait Airways Corp.",
    "N6": "Aero Continente",
    "TX": "Soc.Nouvelle Air Guadeloupe",
    "XE": "ExpressJet Airlines Inc.",
    "APN": "Aspen Airways Inc.",
    "ASU": "Air South",
    "C8": "Cargolux Italia SpA",
    "AMW": "Air Midwest Inc.",
    "SI": "Sierra Pacific Airlines",
    "RD": "Ryan International Airlines",
    "WCI": "Mountainwest Airlines",
    "HER": "Markair Express",
    "SKT": "Skytrain",
    "J5": "Kalinin Aviation LLC d/b/a Alaska Seaplanes",
    "COK": "Coker Aviation Inc.",
    "TEQ": "Transp. Aereos Ejecutivos",
    "BN": "Britannia Airways GmbH",
    "VPJ": "Vintage Props & Jets Inc.",
    "AND": "Southcentral Air Inc.",
    "STW": "Stateswest Airlines",
    "TIA": "Trans Air Inc.",
    "EXP": "Express Airlines II",
    "XDE": "Air Train Inc.",
    "PNS": "Pine State Airlines",
    "HOQ": "Holidair Airways",
    "AFG": "American Flight Group",
    "KA": "Hong Kong Dragonair",
    "EXC": "Executive Charter",
    "SAM": "Samoan Airlines Inc.",
    "AQ": "Aloha Airlines Inc.",
    "9E": "Endeavor Air Inc.",
    "PEQ": "SkyLink Express Inc.",
    "ANI": "Dash Air Corporation",
    "ROQ": "Aero Uruguay",
    "J2": "Azerbaijan Airlines CJSC",
    "GV": "Grant Aviation",
    "DAN": "Danbury Airlines",
    "Q5": "40-Mile Air",
    "KXZ": "Chaparral Airlines Inc.",
    "L2": "Lynden Air Cargo Airlines",
    "GOF": "Copper State Airlines",
    "CRT": "Crested Butte Air Service",
    "4B": "Boutique Air",
    "JER": "Jer-Don Air",
    "KD": "Western Global",
    "BEL": "Bellair Inc.",
    "5Y": "Atlas Air Inc.",
    "SUA": "Sunshine Airlines",
    "LR": "Lacsa",
    "LZQ": "Leisure International Airways Ltd.",
    "PZ": "Lineas Aereas Paraguayas",
    "1ZQ": "Comlux Aruba NV",
    "CRN": "Crown Aviaiton Inc.",
    "3F": "Pacific Airways Inc.",
    "POM": "Pompano Airways",
    "LVA": "Las Vegas Airlines",
    "2AQ": "ABS JETS A.S",
    "MH": "Malaysian Airline System",
    "YTU": "Alaska Central Express",
    "KEQ": "Key Airlines Inc.",
    "MDC": "Midcontinent Airlines",
    "ALS": "Air L.A.",
    "TW": "Trans World Airlines Inc.",
    "WAP": "Arrow Panama",
    "MTV": "Mst Aviation",
    "PNR": "Pioneer Airways",
    "AAI": "Audi Air Inc.",
    "RAI": "Trans States Airlines",
    "HFQ": "Haiti Air Freight Intl",
    "TDQ": "Venexcargo",
    "UN": "Transaero Airlines",
    "Y2": "Globespan Airways Limited d/b/a Flyglobespan",
    "ZX": "Air Georgian",
    "GRA": "Gorda Aero Service",
    "L3": "Lynx Aviation d/b/a Frontier Airlines",
    "FRS": "Four Star Aviation",
    "1VQ": "Scott Air LLC dba Island Air Express",
    "DEA": "Downeast Airlines Inc.",
    "EU": "Ecuatoriana De Aviacion",
    "CHI": "Chitina Air Service",
    "MDU": "Metro Airlines",
    "NEQ": "North East Cargo Airlines",
    "WE": "Centurion Cargo Inc.",
    "F8": "Freedom Airlines d/b/a HP Expr",
    "OWQ": "Ontario Worldair Limited",
    "GLQ": "Allegiant Air",
    "QN": "Royal Air",
    "QR": "Qatar Airways",
    "TER": "Terre Haute Air Commuter",
    "BER": "Bering Air Inc.",
    "ECQ": "Trans American Charter",
    "XAQ": "Cam Air International Inc.",
    "CRH": "Cresent Medivac",
    "TWE": "Trans World Express",
    "TAF": "Tri Air Freight",
    "30Q": "Public Charters Inc. d/b/a North Country Sky d/b/a Regional Sky d/b/a Texas Sky",
    "TSA": "Sierra Pacific Airlines",
    "AGL": "Atlantic Gulf Airlines",
    "FYB": "Flying Boat",
    "8R": "Edelweiss Air Ag",
    "TCO": "Trans-Colorado Airlines",
    "KH": "Aloha Air Cargo",
    "WAR": "Waring Air",
    "AVQ": "Aero Laguna S.A. De C.V.",
    "B0": "Dreamjet SAS Dba La Compagnie",
    "RLQ": "Reliant Airlines",
    "E0": "EOS Airlines Inc.",
    "1IQ": "Jet link AG",
    "B6": "JetBlue Airways",
    "ISL": "Island Airlines",
    "TEN": "Tennessee Airways Inc.",
    "ACQ": "Aeronautica De Cancun",
    "HYA": "Hyannis Aviation",
    "GUN": "Gunnel Aviation Inc.",
    "6F": "Laker Airways Inc.",
    "VIS": "Virgin Islands Seaplane",
    "KIN": "Golden Pacific Airlines",
    "5X": "United Parcel Service",
    "MAV": "Maverick Airways",
    "ZB": "Monarch Airlines",
    "CMD": "Command Airways Inc.",
    "AZE": "Arizona Express",
    "CL": "Capitol International Inc.",
    "POC": "Pocono Airlines Inc.",
    "WST": "Friday Harbor Seaplanes",
    "DVO": "Devoe Airlines",
    "AZP": "Arizona Pacific Airways",
    "PCR": "Pacair",
    "ROE": "Roederer Aviation Inc.",
    "ARS": "Air Sedona",
    "13Q": "Chartright Air Inc.",
    "KEA": "Keene Airways",
    "ARN": "Arnold Aviation",
    "STZ": "Air America Inc.",
    "PT": "Capital Cargo International",
    "ZL": "Affretair",
    "AUQ": "Antonov Design Bureau",
    "IAT": "Iliamna Air Taxi",
    "7C": "Jeju Air Co Ltd.",
    "AKS": "Alaska Seaplane Service",
    "BUR": "Burlington Airways Inc.",
    "ASD": "Amistad Airlines",
    "DA": "Dan Air Services",
    "CSY": "Cape Smythe Air Service",
    "EDE": "Ede Aire",
    "UD": "Fast Air Carrier Ltd.",
    "9I": "Island Air Service",
    "TE": "Air New Zealand",
    "OHZ": "Caribbean Air Services Inc.",
    "FDM": "Freedom Airlines Inc.",
    "3S": "AeroLogic GmbH",
    "AXQ": "Aeron International Airlines Inc.",
    "WEB": "Southeast Alaska Airlines",
    "9L": "Colgan Air",
    "QS": "Travel Service a.s.",
    "8N": "Flagship Airlines Inc.",
    "TSI": "Trans Sierra Airlines Inc.",
    "DUZ": "Summit Airlines Inc.",
    "0J": "JetClub AG",
    "AWQ": "Aermediterranea S.P.A.",
    "ZN": "Key Airlines Inc.",
    "MEA": "Manhattan Express",
    "28Q": "Menagerie Enterprises Inc d/b/a Monarch Air",
    "LCT": "Lake Coastal",
    "I4": "Scott Air LLC dba Island Air Express",
    "API": "Arizona Pacific Inc.",
    "ON": "Air Nauru",
    "NTX": "Grand Airways Inc.",
    "AIM": "Air Mont. Inc.",
    "ACO": "Air Cargo Enterprises Inc.",
    "HRG": "Heritage Airlines",
    "AAQ": "Advance Air Charters",
    "KAQ": "Kalitta Air LLC",
    "CSQ": "Celtic Tech Jet Ltd.",
    "TV": "Haiti Trans Air",
    "DXA": "Dolphin Express",
    "CGE": "Chicago Express Airlines",
    "E8": "USAfrica Airways Inc.",
    "XDF": "Salair Inc.",
    "AHA": "Air Alpha",
    "WTA": "Westates Airlines",
    "NYH": "New York Helicopter Corp.",
    "6P": "Pacific East Air Inc.",
    "QX": "Horizon Air",
    "JB": "Helijet International Inc.",
    "ND": "Intair",
    "AHC": "Air Hawaii",
    "DFS": "Downeast Flying Service",
    "XAR": "Jet Way Inc.",
    "COS": "Cosmopolitan Comm. Airline",
    "XBE": "United Parcel Service",
    "OD": "Emerald Airlines Inc.",
    "EMA": "Emerald Airlines",
    "BAH": "Brennan & Hargreaves Inc.",
    "0CQ": "ACM AIR CHARTER GmbH",
    "THA": "Tropical Helicopter Airways",
    "UT": "Union De Transports Aeriens",
    "TJ": "Jet Charter Service Inc.",
    "COB": "Cotton Belt Aviation Inc.",
    "SOP": "South Pacific Island Airway",
    "BDE": "Jet Express",
    "AOR": "Air New Orleans",
    "MY": "MAXjet",
    "0WQ": "Avjet Corporation",
    "MWA": "Mountain West Airlines",
    "05Q": "Comlux Aviation AG",
    "RVA": "Reeves Air",
    "NUM": "Lake State Airways",
    "KWQ": "Kelowna Flightcraft Air Cha",
    "15Q": "Air Alsie A/S",
    "PON": "Ponderosa Aviation Inc.",
    "K8": "Caribbean Sun Airlines Inc. d/b/a World Atlantic Airlines",
    "WIS": "Air Wisconsin Inc.",
    "TCI": "Trans California Airlines",
    "ABO": "Aeronaves Boringuena Inc.",
    "III": "Idee Industries Inc.",
    "ACK": "Air Central Inc.",
    "WC": "Wien Air Alaska Inc.",
    "PRQ": "Florida West Airlines Inc.",
    "ZAQ": "Zas Airline Of Egypt",
    "Y7": "Flyjet Limited d/b/a Silverjet",
    "BBQ": "Balair Ag",
    "UAI": "Universal Airways Inc.",
    "IG": "Meridiana S.p.A",
    "SAL": "Sallee's Aviation",
    "FED": "Federal Express Corporation",
    "TSF": "American Central Airlines",
    "GAQ": "Galaxy Airlines Inc.",
    "PY": "Surinam Airways Limited",
    "ML": "Aero Costa Rica",
    "EV": "Atlantic Southeast Airlines",
    "UP": "Bahamasair Holding Limited",
    "LFS": "Larrys Flying Service",
    "AGQ": "Argo S. A.",
    "HWK": "Hawking Corporation",
    "GAV": "Gromer Aviation Inc.",
    "CNN": "Centennial Airlines",
    "GKQ": "Laker Airways",
    "LY": "El Al Israel Airlines Ltd.",
    "SCY": "South Coast Airways",
    "ASC": "Air South Inc.",
    "WAL": "Warbelow",
    "PI": "Piedmont Aviation Inc.",
    "EGJ": "Eagle Jet Charter",
    "LAP": "Lapsa",
    "NET": "Nacnet",
    "WWQ": "Worldways Canada Ltd.",
    "BAK": "Bankair Inc.",
    "FBI": "Young Flying Service",
    "BTQ": "Brasair Transportes Aereos",
    "WOA": "Wings Of Alaska",
    "GWE": "Ross Aviation Inc.",
    "CH": "Bemidji Airlines",
    "CSN": "Casino Airlines",
    "JAQ": "Jamaica Air Freighters",
    "2O": "Island Air Service",
    "SER": "Service Aviation Inc.",
    "CAP": "Metro Air Northeast N Y",
    "2UQ": "Svenskt Industriflyg AB",
    "TMQ": "Transportes Aereos Mercantiles Panamericanos S.A",
    "LAW": "Lawrence Aviation",
    "8V": "Wright Air Service",
    "AO": "Aviacion Y Comercio S.A.",
    "9N": "ANA & JP Express Co. Ltd.",
    "ACN": "Alliance Airlines",
    "PH": "Polynesian Airlines Ltd.",
    "WAS": "Wright Air Service",
    "S5": "Shuttle America Corp.",
    "JF": "L.A.B. Flying Service Inc.",
    "FI": "Icelandair",
    "AAL": "Argosy Air Lines Inc.",
    "PAM": "Boston-Maine Airways",
    "LAA": "La Skycab Airline",
    "MA": "Malev Hungarian Airlines",
    "IND": "Indiana Airways Inc.",
    "6R": "Aerounion",
    "OMI": "Omniflight Airways",
    "APQ": "Alas De Transporte International",
    "DIA": "Drummond Island Air",
    "ABQ": "Aeromar C. Por A.",
    "CLQ": "Aero Transcolombiana",
    "GCS": "Midway Commuter",
    "X3": "Hapag-Lloyd Express GmbH",
    "CRQ": "Conner Air Lines Inc.",
    "ENT": "Enterprise Airlines Inc.",
    "AIQ": "Norontair",
    "GLF": "Gulfstream Int",
    "SCO": "Seaco Airlines Inc.",
    "ECR": "East Coast Airways",
    "WS": "Westjet",
    "NJA": "N. J. Merrimack Airlines",
    "FDA": "Florida Airlines Inc.",
    "8F": "Wilburs Inc.",
    "PFA": "Pacificair",
    "XAZ": "Purolator Sky Courier Inc.",
    "NCA": "National Commuter Airlines",
    "ALI": "Brandt Air",
    "CIS": "Cal Sierra Airlines",
    "G3": "VRG Linhas Aereas S A",
    "QK": "Jazz Aviation LP",
    "OMK": "Omak Aviation Airlines",
    "OWS": "Air Kentucky Air Lines",
    "2CQ": "Altius Aviation LLC",
    "HAQ": "Hapag Lloyd Flug.",
    "SRL": "Sterling Air Service",
    "XP": "XTRA Airways",
    "27Q": "Jet Aviation Flight Services Inc.",
    "NCE": "Northcoast Executive",
    "TRO": "Air Molakai",
    "CGA": "Chicago Airlines",
    "24Q": "Blue Jet SP Z o o",
    "WNG": "Wings Airways",
    "ZV": "Air Midwest Inc.",
    "4C": "Aerovias de Intergracian Regional",
    "CAT": "Catalina Airlines Inc.",
    "EFQ": "Trans Europ. Airways France",
    "THQ": "T-Bird Air Inc.",
    "WW": "WOW Air ehf",
    "WL": "World Air Network",
    "MP": "Martinair Holland N.V.",
    "GSC": "GCS Air Service",
    "REA": "Realwest Airlines",
    "AB": "Air Berlin PLC and CO",
    "BOQ": "Transp. Aereos Bolivianos",
    "ZMZ": "Winnipesaukee Aviation Inc.",
    "WLH": "Welch Aviation",
    "AYQ": "Aerodan S.A. De C.V.",
    "RV": "Air Canada rouge LP",
    "TWA": "Trans Western Airlines Utah",
    "NEW": "New England Airlines Inc.",
    "HOZ": "Horizon Air",
    "TPQ": "Aerial Transit Company",
    "TK": "Turk Hava Yollari A.O.",
    "VB": "Aeroenlaces Nacionales S.A. de C.V. d/b/a VivaAerobus",
    "RIA": "Trump Air",
    "U5": "USA 3000 Airlines",
    "SXQ": "Serv De Trans Aereos Fuegui",
    "ZS": "Hispaniola Airways",
    "BMJ": "Bemidji Airlines",
    "FWA": "Far West Airlines",
    "VLA": "Village Aviation",
    "TA": "Taca International Airlines",
    "FM": "Federal Express Corporation",
    "FD": "Air Puerto Rico Airlines",
    "AME": "Americair Inc.",
    "XBD": "Trans Continental Airlines",
    "TBQ": "Triair Bermuda Flt Operations",
    "PEA": "Pearson Aircraft",
    "WIR": "Williams Air Inc.",
    "VAL": "Vieques Air Link Inc.",
    "FLR": "Flirite Inc."
}